import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient, type User } from "npm:@supabase/supabase-js@2.105.0";

type Role = "viewer" | "auditoria" | "calidad" | "editor" | "admin" | "super_admin";
type Action = "list" | "create" | "update" | "set_password" | "toggle" | "delete";
type ProfileRow = { id:string; email:string|null; full_name:string|null; role:Role|string|null; is_active:boolean|null; process_area:string|null; created_at?:string|null; updated_at?:string|null };
type ManagedUser = { id:string; email:string; full_name:string; role:Role; is_active:boolean; process_area:string; created_at:string|null; last_sign_in_at:string|null };

const ROLE_RANK: Record<Role, number> = { viewer:10, auditoria:30, calidad:40, editor:50, admin:80, super_admin:100 };
const VALID_ROLES = new Set<Role>(Object.keys(ROLE_RANK) as Role[]);
const ADMIN_ROLES = new Set<Role>(["admin","super_admin"]);
const EMAIL_RE = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
const CANONICAL_SUPER_ADMIN_EMAIL = "j.perez@ei.com.co";
const MAX_BODY_BYTES = 16 * 1024;
const MAX_USERS = 500;
const SUPABASE_URL = Deno.env.get("SUPABASE_URL") ?? "";
const SUPABASE_SERVICE_ROLE_KEY = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") ?? "";
if (!SUPABASE_URL || !SUPABASE_SERVICE_ROLE_KEY) throw new Error("Faltan secretos de servidor requeridos.");

const service = createClient(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY, { auth:{ autoRefreshToken:false, persistSession:false } });
class HttpError extends Error { status:number; constructor(status:number,message:string){ super(message); this.status=status; } }

function allowedOrigins(){ return (Deno.env.get("PORTAL_ALLOWED_ORIGINS") ?? "https://calidadei-gamma.vercel.app").split(",").map(v=>v.trim()).filter(Boolean); }
function isAllowedOrigin(req:Request){ const origin=req.headers.get("origin"); return !origin || allowedOrigins().includes(origin); }
function corsHeaders(req:Request){ const origin=req.headers.get("origin"); const allowOrigin=origin && isAllowedOrigin(req) ? origin : allowedOrigins()[0]; return { ...(allowOrigin?{"Access-Control-Allow-Origin":allowOrigin}:{}), "Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type", "Access-Control-Allow-Methods":"POST, OPTIONS", "Access-Control-Max-Age":"86400", "Vary":"Origin" }; }
function json(req:Request,body:unknown,status=200){ return new Response(JSON.stringify(body),{status,headers:{...corsHeaders(req),"Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store, max-age=0","Pragma":"no-cache","X-Content-Type-Options":"nosniff","Referrer-Policy":"no-referrer"}}); }
function cleanString(value:unknown,max=250){ return typeof value === "string" ? value.replace(/[\u0000-\u001F\u007F]/g,"").trim().slice(0,max) : ""; }
function normalizeRole(value:unknown):Role { const role=cleanString(value,40) as Role; return VALID_ROLES.has(role)?role:"viewer"; }
function requireRole(value:unknown):Role { const role=cleanString(value,40) as Role; if(!VALID_ROLES.has(role)) throw new HttpError(400,"El rol solicitado no es válido."); return role; }
function roleRank(role:Role|string|null|undefined){ return ROLE_RANK[normalizeRole(role)] ?? 0; }
function requirePassword(value:unknown){
  if(typeof value!=="string" || value.length<12 || value.length>128) throw new HttpError(400,"La contraseña debe tener entre 12 y 128 caracteres.");
  if(!/[a-z]/.test(value)||!/[A-Z]/.test(value)||!/[0-9]/.test(value)||! /[^A-Za-z0-9]/.test(value)) throw new HttpError(400,"La contraseña debe incluir mayúscula, minúscula, número y símbolo.");
  return value;
}
function requireEmail(value:unknown){ const email=cleanString(value,320).toLowerCase(); if(!EMAIL_RE.test(email)) throw new HttpError(400,"El correo no es válido."); return email; }
function authoritativeRole(user:User,profile?:ProfileRow|null):Role { return normalizeRole(profile?.role ?? user.app_metadata?.role); }

async function getProfile(userId:string):Promise<ProfileRow|null>{ const {data,error}=await service.from("profiles").select("id,email,full_name,role,is_active,process_area,created_at,updated_at").eq("id",userId).maybeSingle(); if(error) throw new HttpError(500,"No fue posible consultar el perfil."); return data as ProfileRow|null; }
async function requireCaller(req:Request){ const authorization=req.headers.get("authorization")??""; if(!authorization.startsWith("Bearer ")||authorization.length>8192) throw new HttpError(401,"Sesión requerida."); const token=authorization.slice(7).trim(); const {data,error}=await service.auth.getUser(token); if(error||!data.user) throw new HttpError(401,"La sesión no es válida o expiró."); const profile=await getProfile(data.user.id); if(!profile) throw new HttpError(403,"El usuario no tiene un perfil administrativo."); const role=normalizeRole(profile.role); if(!ADMIN_ROLES.has(role)||profile.is_active===false) throw new HttpError(403,"No tienes permisos administrativos activos."); return {user:data.user,profile,role}; }
async function getTarget(targetId:string){ const profile=await getProfile(targetId); const {data,error}=await service.auth.admin.getUserById(targetId); if(error||!data.user) throw new HttpError(404,"El usuario objetivo no existe."); return {user:data.user,profile}; }
function ensureCanManageTarget(caller:{user:User;role:Role},target:{user:User;profile:ProfileRow|null},options:{allowSelf?:boolean}={}){ if(caller.user.id===target.user.id){ if(options.allowSelf)return; throw new HttpError(400,"No puedes ejecutar esta acción sobre tu propia cuenta."); } const targetRole=authoritativeRole(target.user,target.profile); if(roleRank(targetRole)>=roleRank(caller.role)) throw new HttpError(403,"Solo puedes administrar usuarios con un nivel inferior al tuyo."); }
function ensureCanAssignRole(callerRole:Role,requestedRole:Role,targetEmail:string){ if(requestedRole==="super_admin"&&targetEmail.toLowerCase()!==CANONICAL_SUPER_ADMIN_EMAIL) throw new HttpError(403,"El rol super_admin está reservado para la cuenta principal."); if(callerRole!=="super_admin"&&roleRank(requestedRole)>=roleRank(callerRole)) throw new HttpError(403,"No puedes asignar un rol igual o superior al tuyo."); }
function toManagedUser(user:User,profile?:ProfileRow|null):ManagedUser { return { id:user.id,email:user.email??profile?.email??"",full_name:cleanString(profile?.full_name??user.user_metadata?.full_name,220)||user.email||"Usuario",role:authoritativeRole(user,profile),is_active:profile?.is_active!==false,process_area:cleanString(profile?.process_area??user.user_metadata?.process_area,220),created_at:user.created_at??profile?.created_at??null,last_sign_in_at:user.last_sign_in_at??null }; }

async function listAllAuthUsers(){ const users:User[]=[]; const perPage=100; for(let page=1;page<=Math.ceil(MAX_USERS/perPage);page++){ const {data,error}=await service.auth.admin.listUsers({page,perPage}); if(error) throw new HttpError(500,"No fue posible listar usuarios."); users.push(...data.users); if(data.users.length<perPage)break; } return users.slice(0,MAX_USERS); }
async function actionList(){ const authUsers=await listAllAuthUsers(); const ids=authUsers.map(u=>u.id); let profiles:ProfileRow[]=[]; if(ids.length){ const {data,error}=await service.from("profiles").select("id,email,full_name,role,is_active,process_area,created_at,updated_at").in("id",ids); if(error) throw new HttpError(500,"No fue posible listar perfiles."); profiles=(data??[]) as ProfileRow[]; } const byId=new Map(profiles.map(p=>[p.id,p])); return {users:authUsers.map(u=>toManagedUser(u,byId.get(u.id))).sort((a,b)=>a.full_name.localeCompare(b.full_name,"es"))}; }
async function actionCreate(body:Record<string,unknown>,callerRole:Role){ const email=requireEmail(body.email),password=requirePassword(body.password),fullName=cleanString(body.full_name,220)||email,role=requireRole(body.role),processArea=cleanString(body.process_area,220); ensureCanAssignRole(callerRole,role,email); const {data,error}=await service.auth.admin.createUser({email,password,email_confirm:true,user_metadata:{full_name:fullName,process_area:processArea},app_metadata:{role}}); if(error||!data.user) throw new HttpError(400,error?.message||"No fue posible crear el usuario."); const {data:profile,error:profileError}=await service.from("profiles").upsert({id:data.user.id,email,full_name:fullName,role,process_area:processArea||null,is_active:true,updated_at:new Date().toISOString()},{onConflict:"id"}).select("id,email,full_name,role,is_active,process_area,created_at,updated_at").single(); if(profileError){ await service.auth.admin.deleteUser(data.user.id).catch(()=>undefined); throw new HttpError(500,"Se revirtió la creación porque el perfil no pudo guardarse."); } return {user:toManagedUser(data.user,profile as ProfileRow)}; }
async function actionUpdate(body:Record<string,unknown>,caller:{user:User;role:Role}){ const userId=cleanString(body.user_id,80); if(!userId) throw new HttpError(400,"Falta user_id."); const target=await getTarget(userId); const isSelf=caller.user.id===userId; if(!isSelf)ensureCanManageTarget(caller,target); const currentRole=authoritativeRole(target.user,target.profile),requestedRole=body.role===undefined?currentRole:requireRole(body.role),targetEmail=(target.user.email??target.profile?.email??"").toLowerCase(); if(isSelf&&requestedRole!==currentRole) throw new HttpError(403,"No puedes cambiar tu propio rol desde este panel."); if(!isSelf)ensureCanAssignRole(caller.role,requestedRole,targetEmail); const fullName=body.full_name===undefined?cleanString(target.profile?.full_name??target.user.user_metadata?.full_name,220):cleanString(body.full_name,220); const processArea=body.process_area===undefined?cleanString(target.profile?.process_area??target.user.user_metadata?.process_area,220):cleanString(body.process_area,220); const oldUserMeta=target.user.user_metadata,oldAppMeta=target.user.app_metadata; const safeUserMeta={...oldUserMeta}; delete safeUserMeta.role; const {data:authData,error:authError}=await service.auth.admin.updateUserById(userId,{user_metadata:{...safeUserMeta,full_name:fullName,process_area:processArea},app_metadata:{...oldAppMeta,role:requestedRole}}); if(authError||!authData.user) throw new HttpError(400,authError?.message||"No fue posible actualizar el usuario."); const {data:profile,error:profileError}=await service.from("profiles").upsert({id:userId,email:target.user.email??target.profile?.email??null,full_name:fullName,role:requestedRole,process_area:processArea||null,is_active:target.profile?.is_active!==false,updated_at:new Date().toISOString()},{onConflict:"id"}).select("id,email,full_name,role,is_active,process_area,created_at,updated_at").single(); if(profileError){ await service.auth.admin.updateUserById(userId,{user_metadata:oldUserMeta,app_metadata:oldAppMeta}).catch(()=>undefined); throw new HttpError(500,"El perfil no pudo actualizarse."); } return {user:toManagedUser(authData.user,profile as ProfileRow)}; }
async function actionSetPassword(body:Record<string,unknown>,caller:{user:User;role:Role}){ const userId=cleanString(body.user_id,80); if(!userId)throw new HttpError(400,"Falta user_id."); const password=requirePassword(body.password); const target=await getTarget(userId); ensureCanManageTarget(caller,target,{allowSelf:true}); const {data,error}=await service.auth.admin.updateUserById(userId,{password}); if(error||!data.user)throw new HttpError(400,error?.message||"No fue posible cambiar la contraseña."); return {success:true}; }
async function actionToggle(body:Record<string,unknown>,caller:{user:User;role:Role}){ const userId=cleanString(body.user_id,80); if(!userId)throw new HttpError(400,"Falta user_id."); if(typeof body.is_active!=="boolean")throw new HttpError(400,"is_active debe ser booleano."); const target=await getTarget(userId); ensureCanManageTarget(caller,target); const {data,error}=await service.from("profiles").update({is_active:body.is_active,updated_at:new Date().toISOString()}).eq("id",userId).select("id,email,full_name,role,is_active,process_area,created_at,updated_at").single(); if(error)throw new HttpError(500,"No fue posible cambiar el estado."); return {user:toManagedUser(target.user,data as ProfileRow)}; }
async function actionDelete(body:Record<string,unknown>,caller:{user:User;role:Role}){ const userId=cleanString(body.user_id,80); if(!userId)throw new HttpError(400,"Falta user_id."); const target=await getTarget(userId); ensureCanManageTarget(caller,target); const {error}=await service.auth.admin.deleteUser(userId); if(error){ const message=error.message||"No fue posible eliminar el usuario."; if(/storage|object|owner/i.test(message))throw new HttpError(409,"El usuario posee archivos en Storage. Reasigna o elimina esos archivos antes de borrar la cuenta."); throw new HttpError(400,message); } return {success:true}; }

Deno.serve(async(req:Request)=>{
  const requestId=req.headers.get("x-request-id")??crypto.randomUUID(); const started=performance.now();
  if(!isAllowedOrigin(req)){ console.warn(JSON.stringify({event:"portal_user_admin_rejected_origin",request_id:requestId})); return json(req,{error:"Origen no permitido."},403); }
  if(req.method==="OPTIONS")return new Response(null,{status:204,headers:corsHeaders(req)});
  if(req.method!=="POST")return json(req,{error:"Método no permitido."},405);
  try{
    if(!(req.headers.get("content-type")??"").toLowerCase().startsWith("application/json"))throw new HttpError(415,"Content-Type debe ser application/json.");
    const declared=Number(req.headers.get("content-length")??0); if(declared>MAX_BODY_BYTES)throw new HttpError(413,"Solicitud demasiado grande.");
    const callerData=await requireCaller(req),caller={user:callerData.user,role:callerData.role};
    const raw=await req.text(); if(new TextEncoder().encode(raw).byteLength>MAX_BODY_BYTES)throw new HttpError(413,"Solicitud demasiado grande.");
    let body:Record<string,unknown>; try{body=JSON.parse(raw) as Record<string,unknown>;}catch{throw new HttpError(400,"El cuerpo debe ser JSON válido.");}
    const action=cleanString(body.action,40) as Action; let response:Response;
    switch(action){case"list":response=json(req,await actionList());break;case"create":response=json(req,await actionCreate(body,caller.role),201);break;case"update":response=json(req,await actionUpdate(body,caller));break;case"set_password":response=json(req,await actionSetPassword(body,caller));break;case"toggle":response=json(req,await actionToggle(body,caller));break;case"delete":response=json(req,await actionDelete(body,caller));break;default:throw new HttpError(400,"Acción administrativa no reconocida.");}
    console.log(JSON.stringify({event:"portal_user_admin_completed",request_id:requestId,action,status:response.status,duration_ms:Math.round(performance.now()-started)})); return response;
  }catch(error){ if(error instanceof HttpError){console.warn(JSON.stringify({event:"portal_user_admin_failed",request_id:requestId,status:error.status,duration_ms:Math.round(performance.now()-started)}));return json(req,{error:error.message},error.status);} console.error(JSON.stringify({event:"portal_user_admin_unexpected",request_id:requestId,duration_ms:Math.round(performance.now()-started),error_name:error instanceof Error?error.name:"UnknownError"}));return json(req,{error:"Error interno en la administración de usuarios."},500); }
});
