create table if not exists private.portal_identity_failures (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  failed_at timestamptz not null default now()
);

create index if not exists portal_identity_failures_user_time_idx
  on private.portal_identity_failures(user_id, failed_at desc);

revoke all on private.portal_identity_failures from public, anon, authenticated;
